// Scans practices/*/meta.json and regenerates the site index.
// Run with: node tools/build-index.mjs
// The Pages workflow runs this on every push, so adding a practice folder is
// the only step needed to make it appear on the root page.

import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PRACTICES = join(ROOT, "practices");

const REQUIRED = ["id", "menu", "title", "summary", "why", "added"];

function fail(msg) {
  console.error("build-index: " + msg);
  process.exitCode = 1;
}

const entries = await readdir(PRACTICES, { withFileTypes: true });
const found = [];

for (const entry of entries) {
  if (!entry.isDirectory()) continue;
  const metaPath = join(PRACTICES, entry.name, "meta.json");

  try {
    await stat(metaPath);
  } catch {
    fail(`practices/${entry.name} has no meta.json, skipping.`);
    continue;
  }

  let meta;
  try {
    meta = JSON.parse(await readFile(metaPath, "utf8"));
  } catch (err) {
    fail(`practices/${entry.name}/meta.json is not valid JSON: ${err.message}`);
    continue;
  }

  const missing = REQUIRED.filter((k) => !meta[k]);
  if (missing.length) {
    fail(`practices/${entry.name}/meta.json is missing: ${missing.join(", ")}`);
    continue;
  }

  if (meta.id !== entry.name) {
    fail(`practices/${entry.name}/meta.json has id "${meta.id}" — it must match the folder name.`);
    continue;
  }

  const entryFile = meta.entry || "index.html";
  try {
    await stat(join(PRACTICES, entry.name, entryFile));
  } catch {
    fail(`practices/${entry.name}/${entryFile} does not exist.`);
    continue;
  }

  found.push({
    id: meta.id,
    menu: meta.menu,
    title: meta.title,
    summary: meta.summary,
    why: meta.why,
    topics: Array.isArray(meta.topics) ? meta.topics : [],
    engine: meta.engine || "",
    added: meta.added,
    href: `practices/${meta.id}/${entryFile}`,
  });
}

// Newest first; ties broken by title so the order never wobbles between builds.
found.sort((a, b) => (a.added === b.added ? a.title.localeCompare(b.title) : b.added.localeCompare(a.added)));

const json = JSON.stringify(found, null, 2) + "\n";
await writeFile(join(PRACTICES, "index.json"), json, "utf8");
await writeFile(
  join(ROOT, "assets", "manifest.js"),
  "// Generated by tools/build-index.mjs — do not edit by hand.\nwindow.PRACTICES = " + json,
  "utf8"
);

console.log(`build-index: ${found.length} practice${found.length === 1 ? "" : "s"} indexed.`);
