// Scans practices/*/meta.json and references/*/meta.json and regenerates the site index.
// Run with: node tools/build-index.mjs
// The Pages workflow runs this on every push, so adding a folder is the only
// step needed to make an entry appear on the root page.

import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const REQUIRED = ["id", "menu", "title", "summary", "why", "added"];

// Each collection is a folder of self-contained entries and a global the root
// page reads. Adding a third would be one more line here.
const COLLECTIONS = [
  { dir: "practices", global: "PRACTICES" },
  { dir: "references", global: "REFERENCES" },
];

function fail(msg) {
  console.error("build-index: " + msg);
  process.exitCode = 1;
}

async function scan(collection) {
  const base = join(ROOT, collection.dir);

  let entries;
  try {
    entries = await readdir(base, { withFileTypes: true });
  } catch {
    // A collection with no folder yet is empty, not an error.
    return [];
  }

  const found = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const label = `${collection.dir}/${entry.name}`;
    const metaPath = join(base, entry.name, "meta.json");

    try {
      await stat(metaPath);
    } catch {
      fail(`${label} has no meta.json, skipping.`);
      continue;
    }

    let meta;
    try {
      meta = JSON.parse(await readFile(metaPath, "utf8"));
    } catch (err) {
      fail(`${label}/meta.json is not valid JSON: ${err.message}`);
      continue;
    }

    const missing = REQUIRED.filter((k) => !meta[k]);
    if (missing.length) {
      fail(`${label}/meta.json is missing: ${missing.join(", ")}`);
      continue;
    }

    if (meta.id !== entry.name) {
      fail(`${label}/meta.json has id "${meta.id}" — it must match the folder name.`);
      continue;
    }

    const entryFile = meta.entry || "index.html";
    try {
      await stat(join(base, entry.name, entryFile));
    } catch {
      fail(`${label}/${entryFile} does not exist.`);
      continue;
    }

    found.push({
      id: meta.id,
      menu: meta.menu,
      title: meta.title,
      summary: meta.summary,
      why: meta.why,
      topics: Array.isArray(meta.topics) ? meta.topics : [],
      added: meta.added,
      href: `${collection.dir}/${meta.id}/${entryFile}`,
    });
  }

  // Newest first; ties broken by title so the order never wobbles between builds.
  found.sort((a, b) =>
    a.added === b.added ? a.title.localeCompare(b.title) : b.added.localeCompare(a.added)
  );

  return found;
}

const manifest = ["// Generated by tools/build-index.mjs — do not edit by hand."];
const counts = [];

for (const collection of COLLECTIONS) {
  const found = await scan(collection);
  const json = JSON.stringify(found, null, 2) + "\n";

  // Written per collection as well, so the folder is readable on its own.
  await writeFile(join(ROOT, collection.dir, "index.json"), json, "utf8");
  manifest.push(`window.${collection.global} = ${json.trimEnd()};`);

  counts.push(`${found.length} ${collection.dir}`);
}

await writeFile(join(ROOT, "assets", "manifest.js"), manifest.join("\n") + "\n", "utf8");

console.log("build-index: " + counts.join(", ") + " indexed.");
